typography_spectrum: 0.21270320424810052
color:
  brandStrength: 0.38228878821246326
  lightness: 0.6481349014211446
  saturation: 0.9309757908340544
  rhythmicContrast: 0.5536746631842107
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/82fc8074-5251-4fa4-8754-2583d98d9582.jpg
layout_spectrum: 0.3702099460642785
author:
  name: Status Imperial
  email: info@statusimperial.com
  url: statusimperial.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a111e9a-e15c-46dc-a0b2-cbf99f57234c.jpg
name: brooklynsnextoffer
title: Real Estate is Real Life!
description: Everyday is a new epidsode
