layout_spectrum: 0.480187916662544
typography_spectrum: 0.8031328662764281
color:
  brandStrength: 0.5858940638136119
  lightness: 0.8487374284304678
  saturation: 0.6614929658826441
  rhythmicContrast: 0.7857702132314444
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/82fc8074-5251-4fa4-8754-2583d98d9582.jpg
author:
  name: Status Imperial
  email: info@statusimperial.com
  url: statusimperial.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a111e9a-e15c-46dc-a0b2-cbf99f57234c.jpg
name: brooklynsnextoffer
title: Real Estate is Real Life!
description: Everyday is a new epidsode
