typography_spectrum: 0.5473300707526505
color:
  brandStrength: 0.26559475040994585
  lightness: 0.8191031822934747
  saturation: 0.29816598747856915
  rhythmicContrast: 0.9913388018030673
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.4761314452625811
author:
  name: Status Imperial
  email: info@statusimperial.com
  url: statusimperial.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a111e9a-e15c-46dc-a0b2-cbf99f57234c.jpg
name: brooklynsnextoffer
title: Real Estate is Real Life!
description: Everyday is a new epidsode
