layout_spectrum: 0.06699937395751476
typography_spectrum: 0.567867977079004
color:
  brandStrength: 0.6943516025785357
  lightness: 0.30830089072696865
  saturation: 0.6340249001514167
  rhythmicContrast: 0.42834484460763633
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/82fc8074-5251-4fa4-8754-2583d98d9582.jpg
author:
  name: Status Imperial
  email: info@statusimperial.com
  url: statusimperial.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a111e9a-e15c-46dc-a0b2-cbf99f57234c.jpg
name: brooklynsnextoffer
title: Real Estate is Real Life!
description: Everyday is a new epidsode
